---
abstract: 'simple web application tests'
author:
  - 'L<Aleksei Melezhik|mailto:melezhik@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: swat
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  File::Temp: 0
  Outthentic::DSL: 0.0.3
  Test::Harness: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/melezhik/swat
version: 0.1.68
